
POST http://127.0.0.1:8000/mq4_api/
Content-Type: application/json

{
    "esp32_id": "3C:71:BF:49:2F:8A",
    "ch4": ,
   
}

POST http://127.0.0.1:8000/mq135_api/
Content-Type: application/json

{
    "esp32_id": "3C:71:BF:49:2F:8A",
    "co2": ,
    "nox": 
}

POST http://127.0.0.1:8000/dht22_api/
Content-Type: application/json

{
    "esp32_id": "3C:71:BF:49:2F:8A",
    "temperature": 25.4,
    "humidity": 60.2
}