# Generated by Django 5.1.5 on 2025-01-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_application", "0002_alter_users_options_alter_users_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroilerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="broiler_images/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "fowlrun",
                    models.CharField(
                        choices=[("1", "Fowl Run 1"), ("2", "Fowl Run 2")],
                        default="1",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
