# Generated by Django 5.1.5 on 2025-01-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main_application", "0003_broilerimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="Users_user_set", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="Users_user_set", to="auth.permission"
            ),
        ),
    ]
