# Generated by Django 5.1.5 on 2025-01-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_application", "0004_alter_users_groups_alter_users_user_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="broilerimage",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterField(
            model_name="broilerimage",
            name="image",
            field=models.ImageField(upload_to="broiler_imagies"),
        ),
    ]
