# Generated by Django 5.1.5 on 2025-01-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_application",
            "0005_alter_broilerimage_options_alter_broilerimage_image",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FowlRunConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.IntegerField(null=True)),
                ("humidity", models.IntegerField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "fowlrun",
                    models.CharField(
                        choices=[("1", "Fowl Run 1"), ("2", "Fowl Run 2")],
                        default="1",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
