# Generated by Django 5.1.5 on 2025-03-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_application", "0006_fowlrunconditions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alerts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "fowlrun",
                    models.CharField(
                        choices=[("1", "Fowl Run 1"), ("2", "Fowl Run 2")],
                        default="1",
                        max_length=255,
                    ),
                ),
                ("is_health", models.BooleanField(default=True)),
                (
                    "detection",
                    models.CharField(
                        choices=[("cocci", "cocci"), ("ncd", "ncd"), ("both", "both")],
                        max_length=255,
                    ),
                ),
                ("cocci_pro", models.IntegerField()),
                ("ncd_pro", models.IntegerField()),
                (
                    "detection_method",
                    models.CharField(
                        choices=[
                            ("image_sound", "image_sound"),
                            ("image_dropings", "image_dropings"),
                            ("dropping_sound", "dropping_sound"),
                            ("dropping_image", "dropping_image"),
                            ("all", "both"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AudioFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio", models.FileField(upload_to="audio/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="fowlrunconditions",
            options={"ordering": ["-timestamp"]},
        ),
    ]
