# Generated by Django 5.1.5 on 2025-03-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_application", "0007_alerts_audiofeed_alter_fowlrunconditions_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alerts",
            name="cocci_pro",
        ),
        migrations.RemoveField(
            model_name="alerts",
            name="ncd_pro",
        ),
        migrations.AddField(
            model_name="alerts",
            name="probability",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="alerts",
            name="detection",
            field=models.CharField(
                choices=[("cocci", "cocci"), ("ncd", "ncd"), ("health", "health")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="alerts",
            name="detection_method",
            field=models.CharField(
                choices=[
                    ("sound", "image_sound"),
                    ("image", "image_dropings"),
                    ("all", "both"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="alerts",
            name="is_health",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
