# Generated by Django 5.1.5 on 2025-03-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_application",
            "0008_remove_alerts_cocci_pro_remove_alerts_ncd_pro_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerts",
            name="probability",
            field=models.FloatField(null=True),
        ),
    ]
