# Generated by Django 5.1.5 on 2025-03-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_application", "0009_alter_alerts_probability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerts",
            name="probability",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=7, null=True
            ),
        ),
    ]
