# Generated by Django 5.1.5 on 2025-04-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_application", "0010_alter_alerts_probability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fowlrunconditions",
            name="humidity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fowlrunconditions",
            name="temperature",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
