# Generated by Django 5.1.5 on 2025-04-03 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_application", "0011_alter_fowlrunconditions_humidity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fowlrunconditions",
            name="humidity",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="fowlrunconditions",
            name="temperature",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
    ]
