# Generated by Django 5.1.5 on 2025-04-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_application",
            "0013_remove_audiofeed_audio_audiofeed_analysis_result_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audiofeed",
            options={"ordering": ["timestamp"]},
        ),
    ]
