# Generated by Django 5.1.5 on 2025-05-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_application", "0014_alter_audiofeed_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerts",
            name="diagnosis",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
