# Generated by Django 5.1.5 on 2025-05-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_application", "0015_alerts_diagnosis"),
    ]

    operations = [
        migrations.AddField(
            model_name="broilerimage",
            name="health_status",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
