# Generated by Django 5.1.5 on 2025-05-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_application", "0016_broilerimage_health_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofeed",
            name="fowlrun",
            field=models.CharField(
                choices=[("1", "Fowl Run 1"), ("2", "Fowl Run 2")],
                default="1",
                max_length=255,
            ),
        ),
    ]
