# Generated by Django 5.1.5 on 2025-06-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_application", "0017_audiofeed_fowlrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoundAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sound_count", models.IntegerField()),
                ("sound_status", models.CharField(max_length=20)),
                ("risk_level", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
