# Generated by Django 5.1.5 on 2025-06-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_application", "0018_soundanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="soundanalysis",
            name="prolong_silence",
            field=models.BooleanField(default=False),
        ),
    ]
