# Generated by Django 5.1.5 on 2025-06-10 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_application", "0019_soundanalysis_prolong_silence"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofeed",
            name="humidity",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AddField(
            model_name="audiofeed",
            name="temperature",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
    ]
