# Generated by Django 5.2.5 on 2025-08-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_application", "0021_soundanalysis_humidity_soundanalysis_temperature"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Alerts",
        ),
        migrations.DeleteModel(
            name="AudioFeed",
        ),
        migrations.DeleteModel(
            name="BroilerImage",
        ),
        migrations.DeleteModel(
            name="FowlRunConditions",
        ),
        migrations.DeleteModel(
            name="SoundAnalysis",
        ),
        migrations.RemoveField(
            model_name="users",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="users",
            name="username",
        ),
        migrations.AddField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[("ema", "EMA User"), ("policy", "Policy Maker")],
                default="ema",
                max_length=20,
            ),
        ),
    ]
