# Generated by Django 5.2.5 on 2025-08-12 21:27

import django.db.models.deletion
import main_application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_application",
            "0022_delete_alerts_delete_audiofeed_delete_broilerimage_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Greenhouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("harare", "Harare"),
                            ("bulawayo", "Bulawayo"),
                            ("mutare", "Mutare"),
                        ],
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("owner_name", models.CharField(max_length=100)),
                ("owner_email", models.EmailField(max_length=254)),
                ("owner_phone", models.CharField(max_length=20)),
                ("esp32_id", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Thresholds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("co2_threshold", models.FloatField(default=1000)),
                ("ch4_threshold", models.FloatField(default=50)),
                ("no2_threshold", models.FloatField(default=5)),
                ("temperature", models.FloatField(default=28)),
                ("humidity", models.FloatField(default=70)),
            ],
        ),
        migrations.AlterModelManagers(
            name="users",
            managers=[
                ("objects", main_application.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "gas_type",
                    models.CharField(
                        choices=[
                            ("CO2", "Carbon Dioxide"),
                            ("CH4", "Methane"),
                            ("NOX", "Nitrogen Oxides"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.FloatField()),
                ("threshold", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[("warning", "Warning"), ("critical", "Critical")],
                        max_length=10,
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
                (
                    "greenhouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_application.greenhouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("co2", models.FloatField(help_text="CO₂ ppm")),
                ("ch4", models.FloatField(help_text="CH₄ ppm")),
                ("nox", models.FloatField(help_text="NOₓ ppm")),
                ("temperature", models.FloatField(help_text="°C")),
                ("humidity", models.FloatField(help_text="%")),
                (
                    "greenhouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_application.greenhouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
