# Generated by Django 5.2.5 on 2025-08-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_application",
            "0023_greenhouse_thresholds_alter_users_managers_alert_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thresholds",
            options={"verbose_name_plural": "Thresholds"},
        ),
        migrations.AddField(
            model_name="thresholds",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="thresholds",
            name="ch4_threshold",
            field=models.FloatField(
                default=50, help_text="Maximum CH₄ concentration in ppm"
            ),
        ),
        migrations.AlterField(
            model_name="thresholds",
            name="co2_threshold",
            field=models.FloatField(
                default=1000, help_text="Maximum CO₂ concentration in ppm"
            ),
        ),
        migrations.AlterField(
            model_name="thresholds",
            name="humidity",
            field=models.FloatField(
                default=70, help_text="Maximum humidity percentage"
            ),
        ),
        migrations.AlterField(
            model_name="thresholds",
            name="no2_threshold",
            field=models.FloatField(
                default=5, help_text="Maximum NO₂ concentration in ppm"
            ),
        ),
        migrations.AlterField(
            model_name="thresholds",
            name="temperature",
            field=models.FloatField(default=28, help_text="Maximum temperature in °C"),
        ),
    ]
