# Generated by Django 5.2.5 on 2025-08-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_application",
            "0024_alter_thresholds_options_thresholds_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="ch4",
            field=models.FloatField(blank=True, help_text="CH₄ ppm", null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="co2",
            field=models.FloatField(blank=True, help_text="CO₂ ppm", null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="humidity",
            field=models.FloatField(blank=True, help_text="%", null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="nox",
            field=models.FloatField(blank=True, help_text="NOₓ ppm", null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="temperature",
            field=models.FloatField(blank=True, help_text="°C", null=True),
        ),
    ]
